// reviewParser.js — A utility to extract specific sections from a generated review.

/**
 * Parses the full text of an AI-generated review to find the "Verdict in One Line".
 * This regex is designed to be robust against minor formatting changes from the AI.
 *
 * @param {string} reviewText The full review content generated by the AI.
 * @returns {string|null} The extracted verdict string, or null if not found.
 */
function parseVerdictFromReview(reviewText) {
  if (!reviewText || typeof reviewText !== 'string') {
    return null;
  }

  // *** MODIFICATION START: Make the regex more flexible ***
  // This new regex makes the surrounding bold markers (**) optional and looks for
  // the key phrase followed by a colon and whitespace.
  const verdictRegex = /(?:\*\*)?Verdict in One Line(?:\*\*)?:\s*([^\n]*)/i;
  
  const match = reviewText.match(verdictRegex);

  // If a match is found, the captured group is the verdict text.
  if (match && match[1]) {
    return match[1].trim();
  }

  return null;
}

module.exports = {
  parseVerdictFromReview,
};
