// reviewParser.js — A utility to extract specific sections from a generated review.

/**
 * Parses the full text of an AI-generated review to find the "Verdict in One Line".
 * This regex is designed to be highly robust against formatting variations from the AI.
 *
 * @param {string} reviewText The full review content generated by the AI.
 * @returns {string|null} The extracted verdict string, or null if not found.
 */
function parseVerdictFromReview(reviewText) {
  if (!reviewText || typeof reviewText !== 'string') {
    return null;
  }

  // *** MODIFICATION START: The Definitive, Highly Flexible Regex ***
  // This regex finds a line containing "Verdict in One Line" regardless of
  // surrounding bold markers or quotation marks, and captures the text after the colon.
  // - `^` with the `m` flag matches the start of any line.
  // - `.*` matches any characters (like **, “, •, etc.).
  // - `Verdict in One Line` is the key phrase we're looking for.
  // - `.*:` matches any characters up to the colon.
  // - `\s*` matches any whitespace after the colon.
  // - `([^\n]*)` captures the rest of the line, which is the verdict.
  // - The `i` flag makes it case-insensitive, and `m` makes it multiline-aware.
  const verdictRegex = /^.*Verdict in One Line.*:\s*([^\n]*)/im;
  
  const match = reviewText.match(verdictRegex);

  // If a match is found, the captured group is the verdict text.
  if (match && match[1]) {
    return match[1].trim();
  }
  console.log("[Parser] Verdict could not be found in the review text.");
  return null;
}

module.exports = {
  parseVerdictFromReview,
};
