// reviewParser.js — A utility to extract specific sections from a generated review.

/**
 * Parses the full text of an AI-generated review to find the "Verdict in One Line".
 * This regex is designed to be robust against minor formatting changes from the AI.
 *
 * @param {string} reviewText The full review content generated by the AI.
 * @returns {string|null} The extracted verdict string, or null if not found.
 */
function parseVerdictFromReview(reviewText) {
  if (!reviewText || typeof reviewText !== 'string') {
    return null;
  }

  // Regex looks for "Verdict in One Line" potentially with bold markers (**)
  // and captures everything on that line after the colon. Case-insensitive.
  const verdictRegex = /\*\*Verdict in One Line:\*\*([^\n]*)/i;
  
  const match = reviewText.match(verdictRegex);

  // If a match is found, return the captured group (the verdict text), trimmed of whitespace.
  if (match && match[1]) {
    return match[1].trim();
  }

  return null;
}

module.exports = {
  parseVerdictFromReview,
};
